Meta:
  num_objs: 1  # Single objective

Environment:
  dimensions: [25, 25]
  ep_length: 25
  timestep_penalty: 0
  global_reward_mode: "Aggregated"
  local_reward_mode: "exponential"
  local_reward_kneecap: 10.0
  local_reward_temp: 2
  observation_mode: 'density'
  average_density_readings: False
  poi_obs_temp: 2
  agent_obs_temp: 2
  include_location_in_obs: False

  pois:
    # 5x5 grid positions with coordinates: [3, 8, 13, 18, 23]
    # Omitting the center position (13, 13)
    # Row y = 3
    - obj: 0
      location: [3, 3]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False
    - obj: 0
      location: [8, 3]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False
    - obj: 0
      location: [13, 3]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False
    - obj: 0
      location: [18, 3]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False
    - obj: 0
      location: [23, 3]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False

    # Row y = 8
    - obj: 0
      location: [3, 8]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False
    - obj: 0
      location: [8, 8]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False
    - obj: 0
      location: [13, 8]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False
    - obj: 0
      location: [18, 8]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False
    - obj: 0
      location: [23, 8]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False

    # Row y = 13 (skip [13, 13])
    - obj: 0
      location: [3, 13]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False
    - obj: 0
      location: [8, 13]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False
    - obj: 0
      location: [18, 13]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False
    - obj: 0
      location: [23, 13]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False

    # Row y = 18
    - obj: 0
      location: [3, 18]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False
    - obj: 0
      location: [8, 18]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False
    - obj: 0
      location: [13, 18]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False
    - obj: 0
      location: [18, 18]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False
    - obj: 0
      location: [23, 18]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False

    # Row y = 23
    - obj: 0
      location: [3, 23]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False
    - obj: 0
      location: [8, 23]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False
    - obj: 0
      location: [13, 23]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False
    - obj: 0
      location: [18, 23]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False
    - obj: 0
      location: [23, 23]
      radius: 0.5
      coupling: 1
      obs_window: [0, 100]
      reward: 1
      repeat: False

Agents:
  starting_locs: [[13, 13], [13, 13], [13, 13], [13, 13],
                  [13, 13], [13, 13], [13, 13], [13, 13]]
  num_sensors: [4, 4, 4, 4, 4, 4, 4, 4]
  observation_radii: [5, 5, 5, 5, 5, 5, 5, 5]
  max_step_sizes: [1, 1, 1, 1, 1, 1, 1, 1]