Policy:
  hidden_layers: [16, 16]
  mutation_rate: 0.75
  mutation_scale: 0.5
  weight_init_lim: 0.2
  bias_init_lim: 0.2

Evolutionary:
  pop_size: 200
  num_gens: 2000

Counterfactual:
  num_cf_denom: 5 # team size / num_cf_denom counterfactuals will be used
  random: False